### エラーメッセージ
# テンプレート
# [EXXXX]
# other = こんにちは{{.name}}です。

[E0001]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

[E0002]
other = "データの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0101]
other = "認証に失敗しました。しばらくしてから、もう一度お試しください。"

[E0102]
other = "作成済みのアカウントです。"

[E0103]
other = "ユーザ作成に失敗しました。しばらくしてから、もう一度お試しください。"

[E0104]
other = "ユーザー取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0105]
other = "アカウントが停止されています。"

[E2001]
other = "管理者登録の有効期限が切れました。もう一度登録をやり直してください。"

[E2002]
other = "管理者登録に失敗しました。しばらくしてから、もう一度お試しください。"

[E2003]
other = "管理者ログインに失敗しました。しばらくしてから、もう一度お試しください。"

[E2004]
other = "セッションの有効期限が切れました。もう一度ログインしてください。"

[E2005]
other = "管理者が存在していません。"

[E2006]
other = "管理者取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E2007]
other = "管理者更新に失敗しました。しばらくしてから、もう一度お試しください。"

[E2008]
other = "管理者削除に失敗しました。しばらくしてから、もう一度お試しください。"

[E3001]
other = "商品の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E9001]
other = "署名の検証に失敗しました。しばらくしてから、もう一度お試しください。"

[E9002]
other = "購入情報の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E9003]
other = "購入情報の保存に失敗しました。しばらくしてから、もう一度お試しください。"

[E9004]
other = "購入情報がキャンセルか保留になっています。"

[E9005]
other = "購入情報が一致しません。"

[E9006]
other = "購入情報が正しくありません。"

[E9007]
other = "既に購入済みです。"

[E9101]
other = "通貨の取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E9102]
other = "通貨の発行に失敗しました。しばらくしてから、もう一度お試しください。"

[E9103]
other = "通貨の更新に失敗しました。しばらくしてから、もう一度お試しください。"

[E9901]
ohter = "不正なリクエストです。"

[E9999]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

[IMMEDIATELY_MAINTENANCE_MESSAGE]
other = "緊急メンテナンス中です。"