### エラーメッセージ
# テンプレート
# [EXXXX]
# other = こんにちは{{.name}}です。

[E0001]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"

[E0002]
other = "データの取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0101]
other = "認証に失敗しました。しばらくしてから、もう一度お試しください。"

[E0102]
other = "作成済みのアカウントです。"

[E0103]
other = "ユーザ作成に失敗しました。しばらくしてから、もう一度お試しください。"

[E0104]
other = "ユーザー取得に失敗しました。しばらくしてから、もう一度お試しください。"

[E0105]
other = "アカウントが停止されています。"

[E9901]
ohter = "不正なリクエストです。"

[E9999]
other = "エラーが発生しました。しばらくしてから、もう一度お試しください。"