mysql:
  db_conn: "root:P@ssw0rd!@tcp(db:3306)/appdb?parseTime=True&loc=Asia%2FTokyo"
  read_db_conn: "root:P@ssw0rd!@tcp(readdb:3306)/readdb?parseTime=True&loc=Asia%2FTokyo"
jwt:
  secret: "SpBE*2BBtiN_AQfaiT(jMmWxMqWV4%v2"
  issuer: "http://localhost:8080"
  audience: "http://localhost:8080"
redis:
  conn: "redis:6379"
settings:
  environment: "Development"
  encrypto_only: false
  resource_server: "http://localhost:8080"
cookie:
  key: "session_id"
  host: "localhost"
review_version:
  ios: "1.1.0"
  android: "1.1.0"
requirement_version:
  ios: "1.0.0"
  android: "1.0.0"
load_test_settings:
  enable: "false"